# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 227cd974bf66c65b4a196dcbf6712dbb0d3be335df5d6c82876acd2bb5e317e28804f8a7fe63a9020e8a3b95aef96241b940dcb5c588f0efc3a9fea8860378f8

test:
  secret_key_base: aff6527d6676ec7224280eb8a7219923894366c2fe904c0b24fe9aaf727c694d94d0213e3c43bcc5fcc4805e969bf53719d3c8d47d65c63b141c7d5047cce809

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
